---
title: "Course Mechanics"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---


## About us


## About you

- Your preferred name
- Your pronouns
- Your home department and home lab
- Your research area


## What you need

- Laptop (fully charged)
- Can do attitude
- Patience
- Presence


## Why is this class is structured this way

- We have taught it in the traditional way, and it does not work as well.
    - Working together is key
- Yes it is more effort on your part to coordinate, etc.
    - Teaching is how you know you have learned something


## Book, etc.

There is no one-size-fits-all statistics textbook.

- Any that we chose would be a compromise.
- Lots of free material online.
- Many recommendations on Canvas if you are looking for a book.


## Online lectures

- Available Fridays
- Watch, pause, take notes, re-watch, look up topics you don't understand, etc.


## Grading

Participation: Your participation grade in the course will be a function of:

- Quiz questions (completion)
- Discussion board (completion)
- Problem sets (completion)
- Peer evaluations (both your own completion of and others' evaluations of you)
- In class contributions

Don't worry about what numbers are in the gradebook.


## Grading

Progress Checks:

- Each 4 week block will end with a Progress Check.
    - No new material that week
    - Class time used to answer questions
    - Like a problem set
- You may not work with other members of the class or anyone else on this assignment
- You should use all other available resources (books, notes, lectures, internet, etc.).


## Quiz questions

- In between most of the lectures
    - e.g., Watch a lecture, answer some questions
- Not graded, but you *do* need to complete them.
    - Thoughtful reflection about any you get incorrect


## Problem sets

- Practical experience
- Gradually less guidance
- Experience solving challenges as a team
- All members of the group should participate
- Each group member should submit the same set of answers


## Groups


## Working together

- Many possible successful strategies
    - Remember you have access to lecture code, the google, etc.
- One unsuccessful strategy
    - Splitting up the problem set & not learning all the parts
    - You should only leave class early if your entire group has turned in the problem set


## Peer evaluations


## Reviewing your work

- Problem sets not graded
- You are responsible for checking your group's answers against the answer key
    - Learn from reading other code
    - Many ways to the same outcome


## Typical weekly schedule {.smaller}

**Friday**: Lectures, "quizzes", readings (when applicable) posted online to Canvas

**Tuesday** at midnight:

- Previous week's problem set submitted through Canvas
- Peer evaluations

**Thursday** at midnight:

- Watch lectures
- Weekly quizzes
- Discussion board (note problem set key is available)

**Friday**: Class meeting, discuss any issues from that week (anonymous or not), work together on next problem set.


## Missing class

- Let us know as far in advance as possible
- Work alone or we will create virtual groups


## How do I find help?

- Your group members
- Lecture slides
- Us
- Resources on Canvas
- Links we provide throughout course
- Internet (but use thoughtfully)


## Asking questions

- Each week you will ask a question about what topics were the most challenging to you.
- Start from what you know. Think about what you do not understand.
- Try to be as specific as possible

"I understand that ... I am trying to understand ..."


# "Artificial Intelligence" {background-color="#40666e"}


## Artificial intelligence is not intelligence {.smaller}

- We (unfortunately) use human terms to describe LLMs: "intelligence", "learn", "understand", "think", "know", "hallucinate"
- LLMs generate responses based on probabilities (what character/word comes next?), which are derived from their training data.
- [Large Language Models explained briefly (YouTube)](https://www.youtube.com/watch?v=LPZh9BOjkQs)


:::{.callout-note}
## Predicting based on probability
Predict $y$ if $x = 3$.

$$y = 2x + 3$$
:::


## What are the next two numbers in the sequence?

$$1, 3, 5, 7$$

or

$$1, 3, 5, 7, 17, 19, 21$$

LLMs can answer the first but not the second.


## Ways in which large language models can fail you {.smaller}

- *Outdated and/or incorrect information*: LLMs are trained on historical data, which might have changed or be incorrect
- *Inability to explain*: If you don't code it yourself, you will have greater challenges explaining it
- *Debugging challenges*: If your code doesn't work, then figuring out why will be more challenging
- *Short circuit* the development of problem-solving skills in our learn-by-doing approach
    - Be willing to fail and keep trying.
- *Limiting you creativity and innovation*: There are many ways to solve a coding challenge (think about different recipes for the same dish)


## Please don't use AI to write code for you

- Problem sets are graded for completeness *not* correctness.
- Progress checks will use ideas/code that you have seen before.

"Give me an example of how to change the axis labels in ggplot."


## Course AI guidelines: "AI Integration Allowed: Human-in-the-Loop"

- Generative AI is discouraged, may be used in this course. The content you submit is your responsibility. Be sure your work accurately reflects your understanding and avoids these pitfalls.
- You are responsible for *understanding* what you submit. Simply copying an AI-generated solution does not contribute to gaining understanding.


## Course AI guidelines: "AI Integration Allowed: Human-in-the-Loop"

If you use AI, you must acknowledge it with some variation of this statement:

> "I acknowledge the use of AI in completing this assignment and would like to provide a brief explanation of how I utilized AI, specifically [LLM], as a tool to support my work. For this assignment, I employed [LLM] to [describe the specific purpose or task]. To do so I crafted the following prompts: [List prompts used]"


## Before you ask AI, ask yourself ...

... how will this help me learn?


## This Week's questions

Coming Soon

- Functions
- Organizing data (wide vs. long)
- Organizing and commenting code
- Getting used to R (vs. other languages)


## Where to start

> I am new to all of this, so it's all like a new language to me. I'd say even trouble-shooting or figuring out why something isn't working in R is a concern of mine. As many others have pointed out, the specific character requirement is tricky navigating (missing letters, underscores, slashes, etc.). When practicing with Swirl, it even told me to use spaces between my numbers. Aside from the little stuff, I am most curious how many people first use R in their research. My project is very qualitative, so any ideas as to how I can utilize R would be appreciated.

> Because I do not have a programming background, I mainly need more practice getting used to the syntax, and perhaps learning more about how these tools can be used in practice.


## Where to start

> I am new to this field too, so I still need to learn a lot. I noticed that, when discussing data reproducibility, it was mentioned that using R to process data from Excel and to generate figures can make it easier to annotate the data, which can improve reproducibility.  I always use GraphPad to process data and generate figures. I would like to ask: *in what situations should I choose which software for data processing and figure generation?*

> I gather that with repetition, one would eventually catch on as well, but with starting from a clean slate, I'm wondering *what the best approaches to good study habits would be*.


## Syntax and Debugging

> The largest issue I am having is remembering all of tiny nuances and the syntax that go into the coding. For example, some of the code requires you to put quotation marks around them with others don't, some require commas while others don't, and also I am struggling more just trying to learn and then retain the key words needed for entering data to make items like vectors. *With this in mind I'm more just wondering if there is there a general rule of thumb to follow when writing code or if it is reliant mostly on memorization?*

> One topic I still struggle with is troubleshooting when there is an error in the code. I often get stuck for far to long trying to get a chunk to run.


## Vectorization

> One topic I often find challenging is remembering the differences between R vectors and arrays in other languages. Things like the different tricks R allows, and writing vectorized code.


## Vectors and Printing

```{r}
#| echo: true

y2 <- seq(1, 10, length = 20)
y2
sqrt(y2)
```


## Directories and File Paths

> I have to agree with Mitchell that I was not fully understanding the importance of paths and directories in that tutorial. I wasn't sure how all of the terminology fit into a broader framework of organization.

> I thought one thing that was challenging was the directories and filepath's portion. I did not understand well how to move between these things. I also did not understand the significance of them.


## Directories and File Paths

> I realized that I do not make file paths in the most efficient way - it looks like it can be linked to a general location where it is and not a whole series of folders to go through and are messed up when one changes. More guidance on best practices for that would be helpful!

> I found the “workspace and files” tutorial in Swirl to be challenging and a little confusing. I didn’t quite understand what the directories were, what the point of using them was, and therefore, what I was overall doing while working through the tutorial.


## Storage and Versioning

>  Something I am concerned about with reproducibility is storage space! At what point do you create a new version of something? Where is that line? As someone with limited storage space on my laptop, is there a way to zip up files and have them accessible, but share on storage space? Or is the solution here just to save to a hard drive?

> ... While I don't often lack storage space on my laptop, I do regularly run into issues when trying to share large data files with colleagues especially when zipped files aren't accepted (usually due to security concerns in share drives or emails). *What are the best methods for sharing data/code that takes a lot of space?*


## Images

> Specifically, I’m not sure what the best workflow is for handling images: how they should be stored (file formats, folder structure, etc.), how to import them into R, and which packages or approaches are commonly used for image quantification and analysis.


## Character vectors

> Question: What is the purpose of character vectors? Are they commonly used in the life sciences?


## Rewriting files

> I have a question about saving data when using R. We were told to keep raw data in Excel but for example, when I clean or transform data in R, what is the best way to save those processed data? Sometimes I just rerun the script, but other time I feel like saving the output would be helpful. Should we save them as CSV, or something else? And how do we decide when to save data vs just regenerating it from the code?


## Keeping Up to Date

> One thing I am wondering about is how one should stay up to date about newly released packages and how to assess if they are something worth utilizing. Is this something that is done as needed, or is it something that comes more from referrals from others?
