---
title: "Unit 2 In Class Discussion"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---

```{r}
#| label: setup
#| echo: false

library(tidyverse)
library(readxl)

```


## Today's Discussion

- Rtools, command line tools, updating R & RStudio
- Working directory, data organization, & RStudio Projects
- Plotting (not much discussion today - will plot all semester)
- Tidyverse & Base R


## Rtools, command line tools, updating R & RStudio

- Install git (if asked)
- Install RTools (Windows) or Command Line Tools (MacOS)
- "package [tidyverse] was built..."
- Setting the R version in RStudio

## Working directory, data organization, & RStudio Projects {.smaller}

> I think that I'm still confused on what the working directory actually is. When we change it to "Source File Location," is R moving files around, or just changing where it looks for them when running code? I don't have a clear picture on what exactly the setting does. 

> Can you please explain the working directory and where it "should" be so code can be shared between people/computers? Right now mine is just in my "Documents" through my OnceDrive Do you recommend to move the working directory to a folder outside the "cloud"?

> I wanted to ask for clarification on when y'all said not to use setwd(). Is that just we should avoid using it in the .qmd because of how quarto rendering works, or should we avoid using it in general? 

## Working directory, data organization, & RStudio Projects {.smaller}

> When I was working with some of my own data in R I was trying to import the data and I was having trouble importing specific pages of my excel file. I remember in the video there was a way to do that but I wanted to ask if there is an efficient way to do that? Also when I was trying to set my working directory I kept getting an error. It was on a new script so I am not entirely sure what the issue is.

> I also have a question regarding using git to keep track of code revision. You always set the file to "source file location" but is this redundant if we are using git properly and keeping updated file versions through there? 

> Secondly, (slide 10), when do we need to use "../" to make R look one layer "above" where the file actually is in order to access it?

## Reading from Excel {.smaller}

> When importing data into R from Excel is it necessary or at all beneficial to remove any formulas built into the entries? Or is it best to strip any of that away and do even simpler calculations within R itself?


## Plotting {.smaller}

> Do you have any recommendations on places where one can go to practice working with ggplot? It seems very useful and I would like to have more chances to engage with it.

> I was trying to work with the Iris dataset while watching the lecture, but every time I tried to use ggplot(iris), nothing appeared. When I type glimpse(iris) I am able to see the tibble, but nothing plots when I try to use ggplot. Am I doing something incorrectly, or do I need to download a package or something? 

> I often have errors thrown when using ggplot that take quite a bit of troubleshooting to fix. There are so many options for plotting with ggplot but any helpful tips or resources on the basics would be great!

## Plotting: colors {.smaller}

> In plots like stacked bar charts with many groups, I often end up needing a lot of colors and then some of them become hard to see or the text is not readable anymore. I get stuck trying to fix one or two categories (which I think is the most important ones to show my point) without changing everything else. In cases like this, is it better to rethink the type of plot (instead of forcing more colors)?

> Some of my data when plotted uses too many colors (e.g. stacked bar chart showing top 10 bacterial families between ag and prairie; n <= 20 colors). Very few color packages can plot this many colors, and I end up getting stuck with one or two "bars" being too light/dark of a color for the overlayed white/black text to be visible, and it seems to be impossible to get these one or two "bars" to let me change their font color without changing everything else. What is the best way to handle data visualization when you would need too many colors? Throw the whole graphic out and try something else?

## Plotting: colors {.smaller}


> I really enjoyed using the iris data with ggplot. It was helpful to get a feel for working with an actual dataset and how to alter the graphs. How do you upload new color palettes?

> When you want to use a specific color or a set of colors, do you install them the same way you would install a package, or is there a different method you need to use? Is there also a resource that tells you all the different types of aesthetics and colors you can use?

> A question I have is what are some of the best accessible pallets that are distinctive? Lately I have noticed a lot of graphs have the same color schemes and I want to make sure when presenting my work it is visually accessible and engaging. 

## Tidyverse & Base R {.smaller}

> If I start by using tidyverse. For example, importing a file with read_csv ( ), do I need to keep using tidyverse functions afterward? For example, when selecting rows, should I use MM |> slice (1) instead of MM [1, ]?

> I understand that once dplyr is loaded, you can’t use the base R filter() anymore. Do the base R and dyplr filter() do the same thing? 

> I thought the most challenging part of the last unit was setting up data frames. I struggled with creating the correct orientation to bind the data together from control to repeats. 


## Tidyverse & Base R: Pipes {.smaller}

> Lecture 02-2: I think I understand that pipes help readability and organization, but I'm not sure I'd know when to use it over base R coding. What types of data sets would call for this "piping" a series together? How can I easily identify when I should use it? (Or is it going to become an "all the time" thing?)

> I learned how to use R with the maggitr pipe (%>%) and this is what I default to in my code. I am almost always loading the tidyverse package anyway, so I haven't had problems, but should I look at switching over to the base R pipe? 

## Tidyverse: Pivoting & Joining {.smaller}

> Also, for moving between wide and long format, what if you have multiple columns of data rather than just the one "cases" data file in the example. Will that change what you put in the names_to = "year" and values_to = "cases". I am trying to figure out what we are actually doing with this code. 

> And for the data I work with it comes on many different excel sheets and I often keep things organized by keeping one sample in a file and having the different mixes of information (which need to all be read together) in the sheets. How would one combine information from multiple sheets and multiple files at once?

