---
title: "Unit 7 In Class Discussion"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---

```{r}
#| label: setup
#| message: false
#| warning: false

library(tidyverse)
library(cowplot)

theme_set(theme_cowplot(font_size = 20))

```


## Problem Set 6: Pseudocode

> I found developing the loop for making the plots in problem set 6 to be challenging. I understand the basic structure of a loop and pseudo code in general, but am confused on how to determine if an object is a string and how to properly assign the output of the loop to the 'ii'. 

> Can we go over what pseudocode is? I understood that pseudocode is a kind of workflow for coding, but I didn't understand anything beyond that. I also had a hard time connecting pseudocode to the looping question in PS6.


## Confidence Intervals

> Could we go over quiz 7-1?

> Slide 19 caused confusion in the Intervals video. If we only want to reject it about 10% of the time, why would we make the move to reject if it comes out above the 0.098 and not make the move if it comes out below the 0.098. Wouldn't we have more numbers fall above the 0.098 if they are equally distributed between 0 and 1, leading to more than 10% being rejected? I think I'm interpreting it poorly so was hoping for some more information.

> I think I'm a little confused about what confidence intervals actually tell us. Does not not tell us anything about probability? I know it tells us the percent of time values of the mean fall within the interval, but I'm just a little confused about it overall.


## Questions confidence intervals can't answer

- The *probability* that the true mean is greater than 0 is at least 95%.
- The *probability* that the true mean equals 0 is smaller than 5%
- There is a 95% *probability* that the true mean lies between 0.1 and 0.4.
- The "null *hypothesis*" that the true mean equals 0 is likely to be incorrect.


## Question confidence intervals can answer

- If we were to *repeat* the *experiment* over and over, then in 95% of the trials, the confidence intervals *will contain the true mean*.


## Making Decisions

> Is there a connection between the confidence interval and the p-value (as one can inform the other), or are these separate tests providing supporting information about our data and hypothesis?

> If the t-statistic was closer to the critical value but still below it, would that change how we interpret our results?

> How do you know when to reject a null hypothesis? what do you rely on in your data to make that decision?


## Making Decisions

> I'm a little confused on the concept of power in terms of its relationship to the prevalence of type II errors. I understand that power is inversely related to the prevalence of type II errors, with higher power leading to a lower prevalence of type II errors and lower power leading to a higher prevalence of type II errors, but, if we are unable to know exactly what the true mean is to compare it to the null hypothesis, how can we determine whether the particular level of power we have from a particular sample under analysis is high or low in that scenario?


-----

## Degrees of Freedom

> I'm wondering what exactly are degrees of freedom? I've used the term in stats classes before, but does the term "degrees of freedom" always mean the same thing, conceptually?


