---
title: "Unit 12: In Class Discussion"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---


## Course Evaluations Reminder

- Instructor specific (so there are 2 - sorry!)
- Already have an email
- Open until May 10th
- Can't find email? 
    - Go to [evaluations.missouri.edu](https://evaluation.missouri.edu/)


## Progress Check 3

- Available Monday
- Due on May 16th
- Review and Q & A: Friday May 9 10-11:50
    - Optional
    - Recorded


## PS 11 Stretch Question

- Question about PS11: When finding FWER, what is the difference between finding the estimation of the number of times a false positive occurs (like mean of all false positives) versus finding the FWER using the equation $1-(1-\alpha)^m$? In the code, should we be finding an estimation of the number of times a false positive occurs or using the mpfr()? Wouldn't the mpfr() always be the same regardless of our p values if the number of tests and alpha is the same?


## Randomization

- I'm not very clear about the difference between random sampling and randomization. 
- Why do non-parametric tests have such limited power in comparison to randomization?
- In randomization (12-1, slide 24), the probability of the tails refers to the minimum probability threshold to detect differences is that "new empirical p value" obtained or does that value actually refers to a hypothesis test, checking whether there is an effect or not?
- Quiz 12-1


## GLM

- Could we go over how to choose the appropriate link function for GLMs?
- Could you reiterate the difference between glm vs glmm? Can glmm handle non-normal distributions? Can glm handle random terms and nesting? Broadly, what is a summary of some of the key things to look for in the experimental design, summary stats, and research questions to guide the decision of what model to select?


## GLM

- You mentioned that interpreting results from logistic regression can be difficult when we have multiple predictors. What if the there is no multicollinearity? 
- I'd like to go over quiz two. How can you tell that your value is skewed a biologically significant amount (as opposed to being skewed an insignificant amount) when you only have the intercept for your predictor? 
- In quiz 2. What does it mean to model in function to intercept 1, why was there no predictor variable?


## Dimensionality reduction

- Additional question about PCA - if you know your predictors are highly correlated, is it a good idea to run a PCA and determine the relationship? 
- In Quiz 3, the PCA analysis tested 4 components, with the percentages of the total variance accounted for by each component ranging from around 69% to 3%. Is there a percentage cutoff to exclude certain components?
- Quiz 12-3


## Dimensionality reduction

> A good [dimensionality reduction analysis] "makes sense"; a bad one does not.

<div class="ref">
Tabachnick and Fidell (2019)
</div>


## Multivariate statistics

- We’ve talked a lot about how to deal with more than one predictor as well as multiple ways to work with them and their relationships, but what about when you have multiple related outcome variables? Like if you measure properties of a cell, the properties changing will be your outcome but it can be recorded with many different things. Would this just be running the same model on as many outcome variables as you have? Is it wrong to create different models that best fit for outcome variables that you know are all generally related? Is this considered a violation of independence since the outcome variables are related, or not since the samples themselves are independent?
